apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonedevops
  labels:
    app: FlaskHello
spec:
  replicas: 6
  selector:
    matchLabels:
      app: FlaskHello
  template:
    metadata:
      labels:
        app: FlaskHelo
    spec:
      containers:
        - name: capstonedevops
          image: carlograss92/capstone-project
          ports:
            - containerPort: 80
