apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonedevops
  labels:
    app: FlaskHello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: FlaskHello
  template:
    metadata:
      labels:
        app: FlaskHello
    spec:
      containers:
        - name: capstonedevops
          image: carlograss92/capstone-project
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
