version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies - {{ checksum "requirements.txt"  }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            make install

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            . venv/bin/activate
            make lint

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "requirements.txt" }}

  docker-build-push:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push docker image.
          command: |
            docker build --tag=capstone-project .
            docker login -u ${DOCKER_USERNAME} -p {DOCKER_PASSWORD}
            docker tag capstoneProject carlograss92/capstoneProject:latest
            docker push carlograss92/capstoneProject:latest
workflows:
  default:
    jobs:
      - lint
      - docker-build-push:
          requires:
            - lint
