version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@1.0.3

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies - {{ checksum "requirements.txt"  }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            make install

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            . venv/bin/activate
            make lint

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "requirements.txt" }}

  docker-build-push:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and tang docker image.
          command: |
            docker build --tag=capstone-project .
            docker tag capstone-project carlograss92/capstone-project:latest

      - run:
          name: Push docker image.
          command: |
            docker login -u ${DOCKER_USR} -p ${DOCKER_PASS}
            docker push carlograss92/capstone-project:latest

  deploy-cluster:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install

workflows:
  default:
    jobs:
      # - lint
      # - docker-build-push:
      #     requires:
      #       - lint
      - deploy-cluster
