version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@1.0.3

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies - {{ checksum "requirements.txt"  }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            make install

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            . venv/bin/activate
            make lint

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "requirements.txt" }}

  docker-build-push:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and tang docker image.
          command: |
            docker build --tag=capstone-project .
            docker tag capstone-project carlograss92/capstone-project:latest

      - run:
          name: Push docker image.
          command: |
            docker login -u ${DOCKER_USR} -p ${DOCKER_PASS}
            docker push carlograss92/capstone-project:latest

  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          name for kubernetes cluster.
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yaml
          resource-name: deployment/capstonedevops

workflows:
  deployment:
    jobs:
      - lint
      - docker-build-push:
          requires:
            - lint
      - aws-eks/create-cluster:
          cluster-name: capstonedevops-latest
          requires:
            - docker-build-push
      - create-deployment:
          cluster-latest
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          cluster-latest
          container-image-updates: "capstonedevops=carlograss92/capstone-project"
          post-steps:
            - kubernetes/delete-resource:
                resource-names: capstonedevops
                resource-types: deployment
                wait: true
          record: true
          requires:
            - create-deployment
          resource-name: deployment/capstonedevops
      - aws-eks/delete-cluster:
          cluster-latest
          requires:
            - aws-eks/update-container-image
# workflows:
#   default:
#     jobs:
#       # - lint
#       # - docker-build-push:
#       #     requires:
#       #       - lint
#       - deploy-cluster:
#           cluster-name: capstonedevops-${CIRCLE_WORKFLOW_ID:0:7}
